name: Repo
on:
  workflow_dispatch:
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_A_PAT }}
          ref: lineage-21
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Sync Commits
        run: |
          git remote add upstream https://github.com/PQEnablers-Devices/android_kernel_mediatek_5.10.git
          git fetch upstream lineage-21
          git merge upstream/lineage-21 --ff-only
          git push origin lineage-21
          
