name: Repo
on:
  workflow_dispatch:
jobs:
  copy-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and Push
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.version HTTP/1.1
          git clone --branch lineage-21 --single-branch --progress https://github.com/PQEnablers-Devices/android_kernel_mediatek_5.10.git
          cd android_kernel_mediatek_5.10
          git remote add target https://${{ secrets.REPO_A_PAT }}@github.com/Youffx/android_kernel_xiaomi_mt6785_5.10.git
          git log --reverse --format=%H HEAD | awk 'NR % 30000 == 0' > chunks.txt
          git rev-parse HEAD >> chunks.txt
          while read commit; do
            git push target $commit:refs/heads/lineage-21 --force --progress
          done < chunks.txt
          git push target lineage-21 --force --progress
          
