name: Create Branch

on:
  workflow_dispatch:
    inputs:
      target_commit:
        description: "Masukkan commit hash"
        required: true
        default: ""
      new_branch:
        description: "Nama branch baru"
        required: true
        default: ""

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository A
        run: |
          git clone https://github.com/Youffx/kernel_xiaomi_rosemary.git repoA
          cd repoA
          git fetch --all

      - name: Checkout Specific Commit and Create Branch
        run: |
          cd repoA
          TARGET_COMMIT="${{ github.event.inputs.target_commit }}"
          NEW_BRANCH="${{ github.event.inputs.new_branch }}"
          git checkout -b $NEW_BRANCH $TARGET_COMMIT

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push Branch to Repository A
        env:
          PAT_TOKEN: ${{ secrets.REPO_A_PAT }}
        run: |
          cd repoA
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/Youffx/kernel_xiaomi_rosemary.git
          git push origin $NEW_BRANCH
