name: Fastfetch

on:
  workflow_dispatch:

jobs:
  run-fastfetch:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Fastfetch Binary
        id: cache-fastfetch
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/fastfetch
          key: fastfetch-binary-v2

      - name: Install Fastfetch via GitHub Release
        if: steps.cache-fastfetch.outputs.cache-hit != 'true'
        run: |
          URL=$(curl -s https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest | grep "browser_download_url.*linux-amd64.deb" | cut -d '"' -f 4)
          curl -L -o fastfetch.deb "$URL"
          sudo apt-get install ./fastfetch.deb -y
          sudo cp /usr/bin/fastfetch /usr/local/bin/fastfetch

      - name: Inject Cached Fastfetch
        if: steps.cache-fastfetch.outputs.cache-hit == 'true'
        run: |
          sudo cp /usr/local/bin/fastfetch /usr/bin/fastfetch
          sudo chmod +x /usr/bin/fastfetch

      - name: Create Custom Fastfetch Config
        env:
          USER_SECRET: ${{ secrets.USER }}
        run: |
          mkdir -p ~/.config/fastfetch
          cat << 'EOF' > ~/.config/fastfetch/config.jsonc
          {
              "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
              "logo": {
                  "type": "small",
                  "source": "arch",
                  "color": {
                      "1": "green",
                      "2": "green"
                  }
              },
              "display": {
                  "pipe": false,
                  "color": {
                      "keys": "green",
                      "title": "green"
                  }
              },
              "modules": [
                  {
                      "type": "title",
                      "fqdn": "EOF_ENV_USER_SECRET"
                  },
                  "separator",
                  "os",
                  "host",
                  "kernel",
                  "uptime",
                  "packages",
                  "shell",
                  "display",
                  "terminal",
                  "cpu",
                  "memory",
                  "swap",
                  "disk",
                  "localip",
                  "locale",
                  "break",
                  "colors"
              ]
          }
          EOF
          sed -i "s/EOF_ENV_USER_SECRET/$USER_SECRET/g" ~/.config/fastfetch/config.jsonc

      - name: Run Fastfetch with Custom Config
        run: |
          fastfetch
