name: Fastfetch

on:
  workflow_dispatch:

jobs:
  run-fastfetch:
    runs-on: ubuntu-latest

    steps:
      - name: Install Fastfetch
        run: |
          sudo apt-get update
          sudo apt-get install fastfetch -y

      - name: Run Fastfetch with Custom ASCII and Color
        run: |
          fastfetch --logo debian --color red --pipe false
