name: Build LandVe Kernel (KSU-Next)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by Youffx
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: Youffx/4.19-rosemary-kernel
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bc bison build-essential ccache curl flex git gnupg gperf libelf-dev liblz4-tool libncurses5-dev libssl-dev lzop rsync zip zlib1g-dev

      - name: Setup Clang ZyCromerZ
        run: |
          mkdir -p ${{ github.workspace }}/clang
          wget -q https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20260208-release/Clang-15.0.7-20260208.tar.gz
          tar -xf Clang-15.0.7-20260208.tar.gz -C ${{ github.workspace }}/clang
          rm Clang-15.0.7-20260208.tar.gz
          ${{ github.workspace }}/clang/bin/clang --version

      - name: Setup KSU-Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/Sorayukii/KernelSU-Next/stable/kernel/setup.sh" | bash -s hookless
          mkdir -p drivers/input/touchscreen/mediatek/ft3418_i2c/include/firmware/
          touch drivers/input/touchscreen/mediatek/ft3418_i2c/include/firmware/fw_sample.i
          
      - name: Remove Manual Hooks
        run: |
          sed -i '/ksu_handle_faccessat/d' fs/open.c
          sed -i '/ksu_handle_stat/d' fs/stat.c
          sed -i '/ksu_handle_execve/d' fs/exec.c
          sed -i '/ksu_handle_vfs_read/d' fs/read_write.c

      - name: Modifikasi Defconfig
        run: |
          DEFCONFIG="arch/arm64/configs/rosemary_defconfig"
          
          sed -i '/CONFIG_KSU/d' $DEFCONFIG
          sed -i '/CONFIG_KPROBES/d' $DEFCONFIG
          sed -i '/CONFIG_LOCALVERSION/d' $DEFCONFIG
          sed -i '/CONFIG_EROFS_FS/d' $DEFCONFIG
          sed -i '/CONFIG_SDCARD_FS/d' $DEFCONFIG
          
          {
            echo "CONFIG_KSU=y"
            echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y"
            echo "CONFIG_KSU_EXTRAS=y"
            echo "CONFIG_KSU_LSM_SECURITY_HOOKS=y"
            echo "# CONFIG_KPROBES is not set"
            echo "CONFIG_EROFS_FS=y"
            echo "CONFIG_EROFS_FS_ZIP=y"
            echo "CONFIG_EROFS_FS_POSIX_ACL=y"
            echo "CONFIG_EROFS_FS_SECURITY=y"
            echo "CONFIG_SDCARD_FS=y"
            echo 'CONFIG_LOCALVERSION="-LandVe🥬/Lettuce"'
            echo "CONFIG_LOCALVERSION_AUTO=n"
          } >> $DEFCONFIG

      - name: Build Kernel
        run: |
          export PATH="${{ github.workspace }}/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Youffx"
          export KBUILD_BUILD_HOST="Builder"
          export KBUILD_LSB_VERSION=n
          MAKE_FLAGS=(
              ARCH=arm64
              CROSS_COMPILE=aarch64-linux-gnu-
              CROSS_COMPILE_ARM32=arm-linux-gnueabi-
              CC=clang
              LD=ld.lld
              AR=llvm-ar
              NM=llvm-nm
              OBJCOPY=llvm-objcopy
              OBJDUMP=llvm-objdump
              STRIP=llvm-strip
              CLANG_TRIPLE=aarch64-linux-gnu-
              KBUILD_BUILD_VERSION=1
          )
          
          make O=out "${MAKE_FLAGS[@]}" rosemary_defconfig
          make -j$(nproc --all) O=out "${MAKE_FLAGS[@]}"

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: LandVe-Image
          path: out/arch/arm64/boot/Image.gz-dtb
