name: Build LandVe KSU Next Main

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by Youffx
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: Youffx/4.19-rosemary-kernel
          ref: Susfs
          fetch-depth: 1

      - name: Linux Cip-129
        run: |
          git branch
          git log --oneline -n 5

      - name: KSU Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy

      - name: Manual Hook and SUSFS
        run: |
          curl -LSs https://raw.githubusercontent.com/rksuorg/kernel_patches/master/manual_hook/kernel-4.19_5.4.patch | patch -p1
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/7f2847d.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/27956d2.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/95f8be4.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/03fd2fb.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/6071a48.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/849ca8c.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/bbd5aec.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/6f94042.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/49a5115.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/37ae244.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/0a8cbf3.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/4ba6dccf73a620e565803e5995d5748ecfbb56a2.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/ed8fd10d97a50ec424ae38a40351b5de060f9838.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/e784224542fab4b3888d9103a1f678015221a7d1.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/9ba899398576d329288b023566d3a731470ad13a.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/d406904bb175cb9791b5aed4404df3268859d91b.patch | patch -p1 -f -N --no-backup-if-mismatch
          curl -Ls https://github.com/sidex15/android_kernel_lge_sm8150/commit/bb2f164bc19795ef704f17c82f04885d44421418.patch | patch -p1 -f -N --no-backup-if-mismatch

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bc bison build-essential ccache curl flex git gnupg gperf libelf-dev liblz4-tool libncurses5-dev libssl-dev lzop rsync zip zlib1g-dev

      - name: Setup Clang ZyCromerZ
        run: |
          mkdir -p ${{ github.workspace }}/clang
          wget -q https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20260208-release/Clang-15.0.7-20260208.tar.gz
          tar -xf Clang-15.0.7-20260208.tar.gz -C ${{ github.workspace }}/clang
          rm Clang-15.0.7-20260208.tar.gz
          ${{ github.workspace }}/clang/bin/clang --version

      - name: Modifikasi Defconfig
        run: |
          DEFCONFIG="arch/arm64/configs/rosemary_defconfig"

          sed -i '/CONFIG_LOCALVERSION/d' $DEFCONFIG
          sed -i '/CONFIG_EROFS_FS/d' $DEFCONFIG
          sed -i '/CONFIG_SDCARD_FS/d' $DEFCONFIG
          sed -i '/CONFIG_KSU_SUSFS/d' $DEFCONFIG
          
          {

            echo "CONFIG_EROFS_FS=y"
            echo "CONFIG_EROFS_FS_ZIP=y"
            echo "CONFIG_EROFS_FS_POSIX_ACL=y"
            echo "CONFIG_EROFS_FS_SECURITY=y"
            echo "CONFIG_SDCARD_FS=y"
            echo 'CONFIG_LOCALVERSION="-LandVe👺/悪魔"'
            echo "CONFIG_LOCALVERSION_AUTO=n"
            echo "CONFIG_KSU_SUSFS=y"
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y"
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y"
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y"
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y"
            
          } >> $DEFCONFIG

      - name: Build Kernel
        run: |
          export PATH="${{ github.workspace }}/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Youffx"
          export KBUILD_BUILD_HOST="Builder"
          export KBUILD_LSB_VERSION=n
          MAKE_FLAGS=(
              ARCH=arm64
              CROSS_COMPILE=aarch64-linux-gnu-
              CROSS_COMPILE_ARM32=arm-linux-gnueabi-
              CC=clang
              LD=ld.lld
              AR=llvm-ar
              NM=llvm-nm
              OBJCOPY=llvm-objcopy
              OBJDUMP=llvm-objdump
              STRIP=llvm-strip
              CLANG_TRIPLE=aarch64-linux-gnu-
              KBUILD_BUILD_VERSION=1
          )
          
          make O=out "${MAKE_FLAGS[@]}" rosemary_defconfig
          make -j$(nproc --all) O=out "${MAKE_FLAGS[@]}"

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: LandVe-Image-KSUN-Official
          path: out/arch/arm64/boot/Image.gz-dtb
