name: Upload LLVM 21 to Binaries Repo

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git + Import GPG
        run: |
          git config --global user.name "${{ secrets.USER }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import private.key
          rm -f private.key
          
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
          git config --global commit.gpgsign true

      - name: Download and Extract LLVM 21
        run: |
          mkdir llvm-bin
          cd llvm-bin
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.0/LLVM-21.1.0-Linux-X64.tar.xz
          tar -xf LLVM-21.1.0-Linux-X64.tar.xz --strip-components=1
          rm LLVM-21.1.0-Linux-X64.tar.xz

      - name: Initialize and Push to Empty Repo
        env:
          PAT_TOKEN: ${{ secrets.REPO_A_PAT }}
        run: |
          cd llvm-bin
          git init
          git checkout -b main
          git add .
          git commit -m "Initial commit: Add LLVM 21.1.0 Official Binaries (Linux X64)"
          
          git remote add origin https://x-access-token:${PAT_TOKEN}@github.com/Youffx/llvm-binaries.git
          git push -u origin main --force
          
