name: Sync

on:
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source
        run: git clone --branch aosp https://${{ secrets.REPO_A_PAT }}@github.com/Youffx/kernel_xiaomi_rosemary.git kernel

      - name: Push to Target
        run: |
          cd kernel
          git remote add target https://${{ secrets.REPO_A_PAT }}@github.com/Youffx/project-genesis-aosp-release.git
          git push target aosp --force
          
